name: Deploy Firebase Hosting - VTR-MARINHA

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§© Clonar repositÃ³rio
        uses: actions/checkout@v4

      - name: ðŸ”¥ Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: ðŸš€ Deploy para Firebase Hosting
        env:
          CHAVE_ACESSO_GOOGLE_CREDENTIALS: ${{ secrets.CHAVE_ACESSO_GOOGLE_CREDENTIALS }}
        run: |
          echo "${CHAVE_ACESSO_GOOGLE_CREDENTIALS}" > ${HOME}/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-key.json
          firebase deploy --only hosting --project vtr-marinha
